// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahtpatrcfmnvgvfiocgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFodHBhdHJjZm1udmd2ZmlvY2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDI0NDEsImV4cCI6MjA2MDQ3ODQ0MX0.6BHac8rD0fI0S7WzqM0c7an874Hl8Vs2zWI-VCtxS0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);